spring:
  application:
    name: booking-service

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/booking_db}
    username: ${DATABASE_USERNAME:booking_user}
    password: ${DATABASE_PASSWORD:booking_password}

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      batch-size: 65536
      compression-type: lz4
      properties:
        "[enable.idempotence]": true
        "[linger.ms]": 5

server:
  port: ${SERVER_PORT:8082}

services:
  event:
    base-url: ${EVENT_SERVICE_URL:http://localhost:8081}

app:
  kafka:
    booking-events-topic: booking-events.v1
    outbox-poll-delay-ms: 100