
spring.application.name=booking-service
server.port=${SERVER_PORT:8082}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/booking_db}
spring.datasource.username=${DATABASE_USERNAME:booking_user}
spring.datasource.password=${DATABASE_PASSWORD:booking_password}
spring.jpa.hibernate.ddl-auto=update

services.event.base-url=${EVENT_SERVICE_URL:http://localhost:8081}