server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:8081
              predicates: 
                - Path=/api/events/**
              filters:
                - StripPrefix=1
    
            - id: booking-service
              uri: http://localhost:8082
              predicates: 
                - Path=/api/bookings/**
              filters:
                - StripPrefix=1