
spring.application.name=event-service
server.port=${SERVER_PORT:8081}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/event_db}
spring.datasource.username=${DATABASE_USERNAME:event_user}
spring.datasource.password=${DATABASE_PASSWORD:event_password}
spring.jpa.hibernate.ddl-auto=update

services.booking.base-url=${BOOKING_SERVICE_URL:http://localhost:8082}